name: agri_predict
description: agri_predict application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1

environment:
  sdk: ">=2.2.2 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3

  animated_splash: ^1.0.0
  provider: ^5.0.0
  hive: ^2.0.4
  path_provider: ^2.0.1
  auto_size_text: ^2.1.0
  double_back_to_close_app: ^2.0.1
  http: ^0.13.2
  fluttertoast: ^8.0.6






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/agri.jpeg"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/top_header.png
    - assets/images/splash.png
    - assets/images/gpay.png
    - assets/images/paytm.png
    - assets/images/phonepe.png
    - assets/images/logo.png
    - assets/images/head.png
    - assets/images/agri.jpeg
    - assets/images/autumn.jpeg
    - assets/images/winter.jpeg
    - assets/images/kharif.jpeg
    - assets/images/rabi.jpeg
    - assets/images/summer.jpeg



  fonts:
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/mo_me.ttf

    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/mo_re.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
